/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SessionExpiredRouteImport } from './routes/session-expired'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as OfficerRouteImport } from './routes/officer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ApplicantRouteImport } from './routes/applicant'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OfficerIndexRouteImport } from './routes/officer.index'
import { Route as ApplicantIndexRouteImport } from './routes/applicant.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OfficerSettingsRouteImport } from './routes/officer.settings'
import { Route as OfficerQueueRouteImport } from './routes/officer.queue'
import { Route as OfficerNotificationsRouteImport } from './routes/officer.notifications'
import { Route as OfficerDashboardRouteImport } from './routes/officer.dashboard'
import { Route as OfficerAnalyticsRouteImport } from './routes/officer.analytics'
import { Route as ApplicantUploadRouteImport } from './routes/applicant.upload'
import { Route as ApplicantSettingsRouteImport } from './routes/applicant.settings'
import { Route as ApplicantProfileRouteImport } from './routes/applicant.profile'
import { Route as ApplicantNotificationsRouteImport } from './routes/applicant.notifications'
import { Route as ApplicantDashboardRouteImport } from './routes/applicant.dashboard'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPermissionsRouteImport } from './routes/admin.permissions'
import { Route as AdminOfficersRouteImport } from './routes/admin.officers'
import { Route as AdminModelsRouteImport } from './routes/admin.models'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminConfigRouteImport } from './routes/admin.config'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as ApplicantApplicationsIndexRouteImport } from './routes/applicant.applications.index'
import { Route as OfficerApplicationsIdRouteImport } from './routes/officer.applications.$id'
import { Route as ApplicantApplicationsNewRouteImport } from './routes/applicant.applications.new'
import { Route as ApplicantApplicationsIdRouteImport } from './routes/applicant.applications.$id'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionExpiredRoute = SessionExpiredRouteImport.update({
  id: '/session-expired',
  path: '/session-expired',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerRoute = OfficerRouteImport.update({
  id: '/officer',
  path: '/officer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicantRoute = ApplicantRouteImport.update({
  id: '/applicant',
  path: '/applicant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerIndexRoute = OfficerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfficerRoute,
} as any)
const ApplicantIndexRoute = ApplicantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApplicantRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OfficerSettingsRoute = OfficerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerQueueRoute = OfficerQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerNotificationsRoute = OfficerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerDashboardRoute = OfficerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerAnalyticsRoute = OfficerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => OfficerRoute,
} as any)
const ApplicantUploadRoute = ApplicantUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => ApplicantRoute,
} as any)
const ApplicantSettingsRoute = ApplicantSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ApplicantRoute,
} as any)
const ApplicantProfileRoute = ApplicantProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ApplicantRoute,
} as any)
const ApplicantNotificationsRoute = ApplicantNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ApplicantRoute,
} as any)
const ApplicantDashboardRoute = ApplicantDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ApplicantRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOfficersRoute = AdminOfficersRouteImport.update({
  id: '/officers',
  path: '/officers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModelsRoute = AdminModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const ApplicantApplicationsIndexRoute =
  ApplicantApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => ApplicantRoute,
  } as any)
const OfficerApplicationsIdRoute = OfficerApplicationsIdRouteImport.update({
  id: '/applications/$id',
  path: '/applications/$id',
  getParentRoute: () => OfficerRoute,
} as any)
const ApplicantApplicationsNewRoute =
  ApplicantApplicationsNewRouteImport.update({
    id: '/applications/new',
    path: '/applications/new',
    getParentRoute: () => ApplicantRoute,
  } as any)
const ApplicantApplicationsIdRoute = ApplicantApplicationsIdRouteImport.update({
  id: '/applications/$id',
  path: '/applications/$id',
  getParentRoute: () => ApplicantRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/applicant': typeof ApplicantRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/officer': typeof OfficerRouteWithChildren
  '/otp': typeof OtpRoute
  '/session-expired': typeof SessionExpiredRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/officers': typeof AdminOfficersRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/applicant/dashboard': typeof ApplicantDashboardRoute
  '/applicant/notifications': typeof ApplicantNotificationsRoute
  '/applicant/profile': typeof ApplicantProfileRoute
  '/applicant/settings': typeof ApplicantSettingsRoute
  '/applicant/upload': typeof ApplicantUploadRoute
  '/officer/analytics': typeof OfficerAnalyticsRoute
  '/officer/dashboard': typeof OfficerDashboardRoute
  '/officer/notifications': typeof OfficerNotificationsRoute
  '/officer/queue': typeof OfficerQueueRoute
  '/officer/settings': typeof OfficerSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/applicant/': typeof ApplicantIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/applicant/applications/$id': typeof ApplicantApplicationsIdRoute
  '/applicant/applications/new': typeof ApplicantApplicationsNewRoute
  '/officer/applications/$id': typeof OfficerApplicationsIdRoute
  '/applicant/applications/': typeof ApplicantApplicationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/session-expired': typeof SessionExpiredRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/officers': typeof AdminOfficersRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/applicant/dashboard': typeof ApplicantDashboardRoute
  '/applicant/notifications': typeof ApplicantNotificationsRoute
  '/applicant/profile': typeof ApplicantProfileRoute
  '/applicant/settings': typeof ApplicantSettingsRoute
  '/applicant/upload': typeof ApplicantUploadRoute
  '/officer/analytics': typeof OfficerAnalyticsRoute
  '/officer/dashboard': typeof OfficerDashboardRoute
  '/officer/notifications': typeof OfficerNotificationsRoute
  '/officer/queue': typeof OfficerQueueRoute
  '/officer/settings': typeof OfficerSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/applicant': typeof ApplicantIndexRoute
  '/officer': typeof OfficerIndexRoute
  '/applicant/applications/$id': typeof ApplicantApplicationsIdRoute
  '/applicant/applications/new': typeof ApplicantApplicationsNewRoute
  '/officer/applications/$id': typeof OfficerApplicationsIdRoute
  '/applicant/applications': typeof ApplicantApplicationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/applicant': typeof ApplicantRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/officer': typeof OfficerRouteWithChildren
  '/otp': typeof OtpRoute
  '/session-expired': typeof SessionExpiredRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/officers': typeof AdminOfficersRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/applicant/dashboard': typeof ApplicantDashboardRoute
  '/applicant/notifications': typeof ApplicantNotificationsRoute
  '/applicant/profile': typeof ApplicantProfileRoute
  '/applicant/settings': typeof ApplicantSettingsRoute
  '/applicant/upload': typeof ApplicantUploadRoute
  '/officer/analytics': typeof OfficerAnalyticsRoute
  '/officer/dashboard': typeof OfficerDashboardRoute
  '/officer/notifications': typeof OfficerNotificationsRoute
  '/officer/queue': typeof OfficerQueueRoute
  '/officer/settings': typeof OfficerSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/applicant/': typeof ApplicantIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/applicant/applications/$id': typeof ApplicantApplicationsIdRoute
  '/applicant/applications/new': typeof ApplicantApplicationsNewRoute
  '/officer/applications/$id': typeof OfficerApplicationsIdRoute
  '/applicant/applications/': typeof ApplicantApplicationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/applicant'
    | '/forgot-password'
    | '/login'
    | '/officer'
    | '/otp'
    | '/session-expired'
    | '/signup'
    | '/unauthorized'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/config'
    | '/admin/dashboard'
    | '/admin/models'
    | '/admin/officers'
    | '/admin/permissions'
    | '/admin/settings'
    | '/admin/users'
    | '/applicant/dashboard'
    | '/applicant/notifications'
    | '/applicant/profile'
    | '/applicant/settings'
    | '/applicant/upload'
    | '/officer/analytics'
    | '/officer/dashboard'
    | '/officer/notifications'
    | '/officer/queue'
    | '/officer/settings'
    | '/admin/'
    | '/applicant/'
    | '/officer/'
    | '/applicant/applications/$id'
    | '/applicant/applications/new'
    | '/officer/applications/$id'
    | '/applicant/applications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/session-expired'
    | '/signup'
    | '/unauthorized'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/config'
    | '/admin/dashboard'
    | '/admin/models'
    | '/admin/officers'
    | '/admin/permissions'
    | '/admin/settings'
    | '/admin/users'
    | '/applicant/dashboard'
    | '/applicant/notifications'
    | '/applicant/profile'
    | '/applicant/settings'
    | '/applicant/upload'
    | '/officer/analytics'
    | '/officer/dashboard'
    | '/officer/notifications'
    | '/officer/queue'
    | '/officer/settings'
    | '/admin'
    | '/applicant'
    | '/officer'
    | '/applicant/applications/$id'
    | '/applicant/applications/new'
    | '/officer/applications/$id'
    | '/applicant/applications'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/applicant'
    | '/forgot-password'
    | '/login'
    | '/officer'
    | '/otp'
    | '/session-expired'
    | '/signup'
    | '/unauthorized'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/config'
    | '/admin/dashboard'
    | '/admin/models'
    | '/admin/officers'
    | '/admin/permissions'
    | '/admin/settings'
    | '/admin/users'
    | '/applicant/dashboard'
    | '/applicant/notifications'
    | '/applicant/profile'
    | '/applicant/settings'
    | '/applicant/upload'
    | '/officer/analytics'
    | '/officer/dashboard'
    | '/officer/notifications'
    | '/officer/queue'
    | '/officer/settings'
    | '/admin/'
    | '/applicant/'
    | '/officer/'
    | '/applicant/applications/$id'
    | '/applicant/applications/new'
    | '/officer/applications/$id'
    | '/applicant/applications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApplicantRoute: typeof ApplicantRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OfficerRoute: typeof OfficerRouteWithChildren
  OtpRoute: typeof OtpRoute
  SessionExpiredRoute: typeof SessionExpiredRoute
  SignupRoute: typeof SignupRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-expired': {
      id: '/session-expired'
      path: '/session-expired'
      fullPath: '/session-expired'
      preLoaderRoute: typeof SessionExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer': {
      id: '/officer'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof OfficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applicant': {
      id: '/applicant'
      path: '/applicant'
      fullPath: '/applicant'
      preLoaderRoute: typeof ApplicantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/': {
      id: '/officer/'
      path: '/'
      fullPath: '/officer/'
      preLoaderRoute: typeof OfficerIndexRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/applicant/': {
      id: '/applicant/'
      path: '/'
      fullPath: '/applicant/'
      preLoaderRoute: typeof ApplicantIndexRouteImport
      parentRoute: typeof ApplicantRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/officer/settings': {
      id: '/officer/settings'
      path: '/settings'
      fullPath: '/officer/settings'
      preLoaderRoute: typeof OfficerSettingsRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/queue': {
      id: '/officer/queue'
      path: '/queue'
      fullPath: '/officer/queue'
      preLoaderRoute: typeof OfficerQueueRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/notifications': {
      id: '/officer/notifications'
      path: '/notifications'
      fullPath: '/officer/notifications'
      preLoaderRoute: typeof OfficerNotificationsRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/dashboard': {
      id: '/officer/dashboard'
      path: '/dashboard'
      fullPath: '/officer/dashboard'
      preLoaderRoute: typeof OfficerDashboardRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/analytics': {
      id: '/officer/analytics'
      path: '/analytics'
      fullPath: '/officer/analytics'
      preLoaderRoute: typeof OfficerAnalyticsRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/applicant/upload': {
      id: '/applicant/upload'
      path: '/upload'
      fullPath: '/applicant/upload'
      preLoaderRoute: typeof ApplicantUploadRouteImport
      parentRoute: typeof ApplicantRoute
    }
    '/applicant/settings': {
      id: '/applicant/settings'
      path: '/settings'
      fullPath: '/applicant/settings'
      preLoaderRoute: typeof ApplicantSettingsRouteImport
      parentRoute: typeof ApplicantRoute
    }
    '/applicant/profile': {
      id: '/applicant/profile'
      path: '/profile'
      fullPath: '/applicant/profile'
      preLoaderRoute: typeof ApplicantProfileRouteImport
      parentRoute: typeof ApplicantRoute
    }
    '/applicant/notifications': {
      id: '/applicant/notifications'
      path: '/notifications'
      fullPath: '/applicant/notifications'
      preLoaderRoute: typeof ApplicantNotificationsRouteImport
      parentRoute: typeof ApplicantRoute
    }
    '/applicant/dashboard': {
      id: '/applicant/dashboard'
      path: '/dashboard'
      fullPath: '/applicant/dashboard'
      preLoaderRoute: typeof ApplicantDashboardRouteImport
      parentRoute: typeof ApplicantRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/officers': {
      id: '/admin/officers'
      path: '/officers'
      fullPath: '/admin/officers'
      preLoaderRoute: typeof AdminOfficersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/models': {
      id: '/admin/models'
      path: '/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AdminModelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/applicant/applications/': {
      id: '/applicant/applications/'
      path: '/applications'
      fullPath: '/applicant/applications/'
      preLoaderRoute: typeof ApplicantApplicationsIndexRouteImport
      parentRoute: typeof ApplicantRoute
    }
    '/officer/applications/$id': {
      id: '/officer/applications/$id'
      path: '/applications/$id'
      fullPath: '/officer/applications/$id'
      preLoaderRoute: typeof OfficerApplicationsIdRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/applicant/applications/new': {
      id: '/applicant/applications/new'
      path: '/applications/new'
      fullPath: '/applicant/applications/new'
      preLoaderRoute: typeof ApplicantApplicationsNewRouteImport
      parentRoute: typeof ApplicantRoute
    }
    '/applicant/applications/$id': {
      id: '/applicant/applications/$id'
      path: '/applications/$id'
      fullPath: '/applicant/applications/$id'
      preLoaderRoute: typeof ApplicantApplicationsIdRouteImport
      parentRoute: typeof ApplicantRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminModelsRoute: typeof AdminModelsRoute
  AdminOfficersRoute: typeof AdminOfficersRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminModelsRoute: AdminModelsRoute,
  AdminOfficersRoute: AdminOfficersRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApplicantRouteChildren {
  ApplicantDashboardRoute: typeof ApplicantDashboardRoute
  ApplicantNotificationsRoute: typeof ApplicantNotificationsRoute
  ApplicantProfileRoute: typeof ApplicantProfileRoute
  ApplicantSettingsRoute: typeof ApplicantSettingsRoute
  ApplicantUploadRoute: typeof ApplicantUploadRoute
  ApplicantIndexRoute: typeof ApplicantIndexRoute
  ApplicantApplicationsIdRoute: typeof ApplicantApplicationsIdRoute
  ApplicantApplicationsNewRoute: typeof ApplicantApplicationsNewRoute
  ApplicantApplicationsIndexRoute: typeof ApplicantApplicationsIndexRoute
}

const ApplicantRouteChildren: ApplicantRouteChildren = {
  ApplicantDashboardRoute: ApplicantDashboardRoute,
  ApplicantNotificationsRoute: ApplicantNotificationsRoute,
  ApplicantProfileRoute: ApplicantProfileRoute,
  ApplicantSettingsRoute: ApplicantSettingsRoute,
  ApplicantUploadRoute: ApplicantUploadRoute,
  ApplicantIndexRoute: ApplicantIndexRoute,
  ApplicantApplicationsIdRoute: ApplicantApplicationsIdRoute,
  ApplicantApplicationsNewRoute: ApplicantApplicationsNewRoute,
  ApplicantApplicationsIndexRoute: ApplicantApplicationsIndexRoute,
}

const ApplicantRouteWithChildren = ApplicantRoute._addFileChildren(
  ApplicantRouteChildren,
)

interface OfficerRouteChildren {
  OfficerAnalyticsRoute: typeof OfficerAnalyticsRoute
  OfficerDashboardRoute: typeof OfficerDashboardRoute
  OfficerNotificationsRoute: typeof OfficerNotificationsRoute
  OfficerQueueRoute: typeof OfficerQueueRoute
  OfficerSettingsRoute: typeof OfficerSettingsRoute
  OfficerIndexRoute: typeof OfficerIndexRoute
  OfficerApplicationsIdRoute: typeof OfficerApplicationsIdRoute
}

const OfficerRouteChildren: OfficerRouteChildren = {
  OfficerAnalyticsRoute: OfficerAnalyticsRoute,
  OfficerDashboardRoute: OfficerDashboardRoute,
  OfficerNotificationsRoute: OfficerNotificationsRoute,
  OfficerQueueRoute: OfficerQueueRoute,
  OfficerSettingsRoute: OfficerSettingsRoute,
  OfficerIndexRoute: OfficerIndexRoute,
  OfficerApplicationsIdRoute: OfficerApplicationsIdRoute,
}

const OfficerRouteWithChildren =
  OfficerRoute._addFileChildren(OfficerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApplicantRoute: ApplicantRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OfficerRoute: OfficerRouteWithChildren,
  OtpRoute: OtpRoute,
  SessionExpiredRoute: SessionExpiredRoute,
  SignupRoute: SignupRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
